<a href="https://colab.research.google.com/github/jagadeesh1972/mlworkshop/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
li=np.array([[1,2,3],[4,5,6]])
print(li)

[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
a=np.array([1,3,5,7])
b=np.array([2,4,6,8])
c=np.array([9,10,11,12])
abc=np.array([a,b,c])
print(abc)
print(abc.shape)
n=abc.reshape(2,6)
print(n)
print(n.shape)
n=abc.reshape(3,4)
print(n)
print(n.shape)
print(n[1,2])



[[ 1  3  5  7]
 [ 2  4  6  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  3  5  7  2  4]
 [ 6  8  9 10 11 12]]
(2, 6)
[[ 1  3  5  7]
 [ 2  4  6  8]
 [ 9 10 11 12]]
(3, 4)
6


In [18]:
zeroarray=np.zeros((3,3))
print(zeroarray)
print(abc[:,1:3:1])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 3  5]
 [ 4  6]
 [10 11]]


In [21]:
rep=np.where(abc>5,abc,5)
print(rep)

[[ 5  5  5  7]
 [ 5  5  6  8]
 [ 9 10 11 12]]


In [24]:
sm=np.array([1,2,3])
mod=np.array([4,5,6])
sum=np.add(sm,mod)
print(sum)

[5 7 9]


In [26]:
print(np.sum(abc))
print(np.cumsum(abc))

78
[ 1  4  9 16 18 22 28 36 45 55 66 78]


In [31]:
a=np.array([1,2,3])
b=np.array([3,4,5])
c=np.add(a,b)
print(np.sum(c))
print(np.cumsum(c))

18
[ 4 10 18]


In [6]:
a=np.array([1,2,3])
print(np.prod(a))
print(np.cumprod(a))

6
[1 2 6]


In [7]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]
